require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'childAlarmClock' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  permissions_path = '../node_modules/react-native-permissions/ios'  
  
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"
  
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec" 
  
  pod 'Permission-Notifications', :path => 
  "#{permissions_path}/Notifications.podspec"

  target 'childAlarmClockTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'childAlarmClock-tvOS' do
  # Pods for childAlarmClock-tvOS

  target 'childAlarmClock-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
